export const CHANGE_PRODUCTION_INFORMATION = 'CHANGE_PRODUCTION_INFORMATION'
export const CHANGE_PRODUCTION_IMAGES = 'CHANGE_PRODUCTION_IMAGES'
export const CHANGE_RECOMMEND_IMAGES = 'CHANGE_RECOMMEND_IMAGES'
